In [515]:
import DataProvider
prov = DataProvider.DataProvider()

[new value of  11
--new value of  13
--new value of  31
--new value of  49
-------new value of  50
---new value of  62
-------------------new value of  63
---------------------------------------------

/home/rezi/Desktop/Machine Learning/ML_Final_project/DataProvider.py:135: RuntimeWarning: invalid value encountered in true_divide
  spectrogram = (spectrogram - mean) / std


----------------------------------------------new value of  70
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------new value of  72
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]
[###################################################################################################################################################################################################################################################################################################################################################################

In [516]:
import numpy as np
X = list()
y = list()
trainVal = list()

In [517]:
while prov.hasNext(True):
    Xt, yt = prov.next(True)
    for i in range(len(yt)):
        if yt[i] == 1:
            trainVal.append(i+1)
            
    X.append(Xt)
    y.append(yt)

In [518]:
X = np.nan_to_num(np.matrix(X))
y = np.matrix(y)

X.shape, y.shape

((688, 1440), (688, 5))

In [519]:
X2 = list()
y2 = list()
actualVal = list()

In [520]:
while prov.hasNext(False):
    X2t, y2t = prov.next(False)
    actualVal.append(y2t)
    
    k = np.zeros(5)
    k[y2t - 1] = 1
    
    X2.append(X2t)
    y2.append(k)

In [521]:
X2 = np.nan_to_num(np.matrix(X2))
y2 = np.matrix(y2)

X2.shape, y2.shape

((27, 1440), (27, 5))

In [535]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers

In [536]:
model = Sequential()
sgd = optimizers.SGD(lr=0.005, decay=1e-6, momentum=0.9, nesterov=True)

In [537]:
model.add(Dense(units=64, activation='relu', input_dim = prov.returnSizeOfEverySpectogram()))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(units=5, activation='softmax'))

In [538]:
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

In [539]:
model.fit(X, y, epochs=300, batch_size=128)

Epoch 1/300
688/688 [==============================] - 1s 2ms/step - loss: 1.6424 - accuracy: 0.1890
Epoch 2/300
688/688 [==============================] - 0s 81us/step - loss: 1.6278 - accuracy: 0.2006
Epoch 3/300
688/688 [==============================] - 0s 74us/step - loss: 1.6154 - accuracy: 0.2224
Epoch 4/300
688/688 [==============================] - 0s 77us/step - loss: 1.6048 - accuracy: 0.2311
Epoch 5/300
688/688 [==============================] - 0s 79us/step - loss: 1.5952 - accuracy: 0.2529
Epoch 6/300
688/688 [==============================] - 0s 69us/step - loss: 1.5864 - accuracy: 0.2631
Epoch 7/300
688/688 [==============================] - 0s 72us/step - loss: 1.5778 - accuracy: 0.2863
Epoch 8/300
688/688 [==============================] - 0s 77us/step - loss: 1.5698 - accuracy: 0.3169
Epoch 9/300
688/688 [==============================] - 0s 102us/step - loss: 1.5619 - accuracy: 0.3372
Epoch 10/300
688/688 [==============================] - 0s 199us/step - loss: 1.55

In [540]:
import matplotlib.pyplot as plt

# Plot training & validation accuracy values
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

27/27 [==============================] - 0s 9ms/step


In [541]:
loss_and_metrics = model.evaluate(X2, y2, batch_size=512)

array([[5.34578681e-01, 1.23594226e-02, 2.81793270e-02, 3.49510461e-01,
        7.53720328e-02],
       [2.33242288e-04, 3.64498090e-04, 1.71751508e-05, 9.57861960e-01,
        4.15231772e-02],
       [1.36340270e-03, 1.87433703e-04, 8.78209721e-06, 9.42333162e-01,
        5.61072528e-02],
       [2.02716840e-03, 9.67701793e-01, 2.23927312e-02, 2.00203084e-03,
        5.87624591e-03],
       [4.43141460e-01, 2.90865381e-03, 1.73553475e-03, 5.49348176e-01,
        2.86619854e-03],
       [4.81324922e-03, 7.09126180e-04, 1.00595840e-04, 8.36643875e-01,
        1.57733187e-01],
       [4.26804423e-02, 2.32373551e-03, 9.54029977e-01, 6.29761489e-05,
        9.02869797e-04],
       [5.57964519e-02, 4.55313875e-06, 9.44196284e-01, 5.56140911e-09,
        2.65740118e-06],
       [2.96412400e-05, 9.36247688e-03, 1.09455104e-04, 8.18904140e-04,
        9.89679575e-01],
       [5.13086794e-03, 2.08104122e-02, 9.39863920e-01, 2.35694996e-03,
        3.18377540e-02],
       [1.98203576e-04, 2.6300

In [542]:
pred = model.predict(X2, batch_size=128)

array([1, 4, 4, 2, 4, 4, 3, 3, 5, 3, 5, 1, 1, 5, 4, 5, 1, 4, 1, 4, 1, 1,
       3, 5, 3, 5, 5])

In [428]:
pr = np.argmax(pred, axis=1)+1
pr

array([4, 5, 5, 5, 4, 5, 5, 1, 5, 2, 4, 3, 5, 5, 5, 3, 1, 5, 3, 5, 4, 3,
       5, 5, 2, 5, 1])

In [543]:
correct = [1 if a == b else 0 for (a, b) in zip(pr, actualVal)]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ("Accuracy: " + str(accuracy * 100) + "%")

Accuracy: 55.55555555555556%


In [544]:
for i in pred:
    count = sum(i)
    for j in range(len(i)):
        i[j] = i[j] / count

In [545]:
import copy
countGrade = copy.deepcopy(actualVal)


[4,
 4,
 4,
 2,
 4,
 1,
 3,
 5,
 2,
 3,
 2,
 1,
 1,
 5,
 4,
 5,
 2,
 5,
 3,
 5,
 1,
 5,
 3,
 1,
 3,
 5,
 2]

In [546]:
for i in range(len(countGrade)):
    ans = actualVal[i]
    countGrade[i] = pred[i][ans-1]

In [547]:
result = sum(countGrade) / len(countGrade)
result

0.5261595160480671